### ISSUE TITLE
Module not found during installation

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibojit#63]
As observed today, the approach in https://github.com/qiboteam/qibojit/blob/main/setup.py#L29 only works if the qibo package is already installed, otherwise the code raises an module error, but installs properly. 

The problem is that, even if qibo is required, the current pip installation does not register qibo (refresh its environment) before executing this line, thus it raises and error and proceeds with python setup.py install (which now has qibo available).

In principle this is not a big deal, I think we have 3 options:
1. keep as it is
2. update the docs explaining that qibo must be installed beforehand
3. remove the precompilation from setup.py

@stavros11, @mlazzarin, @andrea-pasquale what is you opinion?

**Comment by stavros11** [comment]
> @stavros11, @mlazzarin, @andrea-pasquale what is you opinion?

I guess we added the precompilation in setup.py to get better performance later when executing scripts, but I do not remember exactly what is the advantage or also something could change with a later PR. Does it make sense to do some benchmarks with and without the precompilation and see if there is any advantage? If the difference is negligible we could go with 3, which is the simplest in terms of maintenance and from the user perspective.

**Comment by scarrazza** [comment]
If we drop this I expect that the first time the user imports qibojit, the import time + dry-run will take an extra 30s to start (where we cache kernels). As I said option 1 and 2 are not too bad, but border line.

**Comment by andrea-pasquale** [comment]
> @stavros11, @mlazzarin, @andrea-pasquale what is you opinion?

I mean from a user perspective I found it quite difficult that someone would install qibojit before qibo. I'm guessing that the safest option would be 2 if we want to document this behaviour. Otherwise option 1 also sounds good to me.

**Comment by scarrazza** [comment]
@stavros11 could you please test the performance when doing 3?

**Comment by stavros11** [comment]
> @stavros11 could you please test the performance when doing 3?

I did the following tests in different clean environments in qibomachine:

1. Installed qibo with `pip install .` and then qibojit with the same command. It worked without any errors but it seems that the precompilation step did not work and in the first run I got an import time of around 38sec. In the second run the import time was 0.8sec.
2. Installed qibo with `python setup.py install` and then qibojit with the same command. The qibojit installation failed saying that numba is required so I installed numba using pip and tried again. Now precompilation worked as qibojit installation took about 30sec while throwing many messages (not errors). Then import time was down to 0.8sec from the first run.
3. Removed the `CustomInstall` lines from setup.py (point 3) and installed both qibo and qibojit with `python setup.py install`. Now installation worked ok but the first time I ran a script I got an error that `llvmlite` is missing and then that numpy version is not compatible with numba, so I had to do `pip install --upgrade numba` manually to fix these. After fixing the first import took 38sec and then down to 0.8sec as expected.

I did not observe differences in dry run/simulation times, perhaps the first dry run without precompilation is slighlty larger but this may just be noise. Summarizing, the effect of removing precompilation is exactly that the first time something is executed after installation there'll be a compilation overhead for ~38sec (depending on machine).

Generally I am concerned that if we remove precompilation these 30secs will discourage first time users from using qibojit, unless we clearly state it in the docs. But still, it is more natural for installation to take 30secs rather than a first execution of a simple circuit.

Other than that, I am also concerned about the installation issues described above, eg. why precompilation did not work in case 1 and why I had to install numba manually in 2 and 3. Has anyone observed these issues?

**Comment by scarrazza** [comment]
@stavros11 thanks. I cannot confirm the numba/numpy/llvm issues you have raised, in principle if you start from a new environment qibojit will download numba->numpy->llvm accordingly.

At this point, I would suggest to keep the current approach as it, precompilation during installation. Nevertheless, it seems like our actions in qibo are failing for linux, I am not sure we understand why.

**Comment by stavros11** [comment]
> @stavros11 thanks. I cannot confirm the numba/numpy/llvm issues you have raised, in principle if you start from a new environment qibojit will download numba->numpy->llvm accordingly.

That's what I also expected and it works with `pip install .` but not with `python setup.py install`. I am using Python 3.8 and `virtualenv` to create the environment. If I try to install qibojit directly using `python setup.py install` I get
```
ModuleNotFoundError: No module named 'qibo'
```
during installation. If I use `pip install .` I get some errors but installation works, as you say.

> At this point, I would suggest to keep the current approach as it, precompilation during installation. 

I agree. Other than the errors that appear during installation, there is no other issue with this, right?

> Nevertheless, it seems like our actions in qibo are failing for linux, I am not sure we understand why.

I thought it was something related to qiboteam/qibo#539 but I see that it also happens to master. Do you think it is related to merging #64? I believe it is the only change since these actions started failing.

**Comment by scarrazza** [comment]
Not really, this action is using a previous commit and linux seems stuck: https://github.com/qiboteam/qibo/actions/runs/1755758908

**Comment by scarrazza** [comment]
Btw, I cannot reproduce this issue on my current environment.

**Comment by scarrazza** [comment]
Closing this given that #66 is merged.
